---
- hosts: all
  gather_facts: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600
      when: ansible_facts['distribution']=="Ubuntu"

    - name: configure elasticsearch hosts file
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0642
      become: yes

  tasks:
    - name: Install Openjdk-11 
      become: yes
      apt:
       name: "{{ jdk_ubuntu }}"
       state: present
      when: ansible_facts['distribution']=="Ubuntu"

- hosts: elastic  
  roles:
    - elastic

- hosts: elastic_master
  roles:
    - elastic_master

- hosts: elastic_datanode
  roles:
    - elastic_datanode

- hosts: kibana
  roles:
    - kibana

- hosts: logstash
  roles:
    - logstash
    - filebeat
